### ISSUE TITLE
New feature: Derive imported function name from corresponding export list.

### ISSUE THREAD

**Issue by MarekKnapek** [hfiref0x/WinDepends#1]
**Describe the bug**
Sometimes a module imports functions by ordinal, thus user can not see name of imported function. But if the user happens to have corresponding DLL on their disk, the function name could be derived from that DLL. Lookup the ordinal and display the function name.

**To Reproduce**
 - Open `WinDepends.exe`.
 - Analyze file, select `WinDepends.Core.x64.exe`.
 - Expand the tree on the left (should be already expanded by one level in my opinion).
 - Click on `WS2_32.dll`.
 - See that function ordinal `3` is being imported. But what is its name?
 - You need to click the function, invoke context menu and jump down to linked export to learn it was `closesocket`.
 - Maybe add new feature that such function names could be populated automagically. Maybe using different color or something so the user knows the names were in fact synthesized.
 - My tool does exactly this and I find it useful. Sadly I have no time to develop it further. https://github.com/MarekKnapek/DependencyViewer

**Expected behavior**
Lookup the ordinal and display the function name.

**Screenshots**
![dwa](https://github.com/user-attachments/assets/f20e64c2-e881-4581-b521-8ebd4dddf6b6)
![dwb](https://github.com/user-attachments/assets/2fd40b0f-baf1-49d1-a5f5-e7b829c8f5f0)

**Desktop (please complete the following information):**
 - Windows Server 2022 x64 latest updates
 - Microsoft Windows [Version 10.0.20348.2849]

**Files**
no

**Additional context**
Feel free to borrow / steal source code and / or any ideas from my project.

**Comment by hfiref0x** [comment]
Implemented in [3c56df7](https://github.com/hfiref0x/WinDepends/commit/3c56df72e15953c79c04749ebf6521beb88d3c98)
