### ISSUE TITLE
Dll Max Depth Level

### ISSUE THREAD

**Issue by mirh** [hfiref0x/WinDepends#10]
**Describe the bug**
Title

**To Reproduce**
1. Open rpcss.dll
2. Click on "propagate analysis settings on dependencies"

**Expected behavior**
There is at least a difference at all with the case where I don't enable the setting

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Version 10.0.19045.4780

**Comment by hfiref0x** [comment]
This setting apply to all module dependent modules the following options if they are selected:

- enable transport statistics
- sets minimal address to given when rellocating image

Except statistics display there should be no visible change.

Example (openning rpcss.dll):
![image](https://github.com/user-attachments/assets/2a0321b8-4a60-4c34-a23b-5c26d70b1940)

Output, clearly visible stats for each module:
![image](https://github.com/user-attachments/assets/bf324259-5e8f-44d7-b4b4-08b54ebd74a6)

Now disable this setting:
![image](https://github.com/user-attachments/assets/7c536f62-85ed-450d-99cf-1e3f661cd6a7)

Result:
![image](https://github.com/user-attachments/assets/0d059c30-6187-4ff8-bc65-ea12ab986d23)

The stat command apply only on first (main) module and doesn't apply to it dependents.

Normally, if not using stats command settings, this will not show you anything that will be different to usual scan. This is made primarily for modules that require relocation processing to be parsed and displayed correctly.

**Comment by mirh** [comment]
Oh, uhm... then I think I very much misunderstood its purpose.

What if I wanted to have a list of all the dependents recursively?

**Comment by hfiref0x** [comment]
> What if I wanted to have a list of all the dependents recursively?

It already does this. By default module tree depth is limited to 2 levels. You can adjust this up to 10 levels via Configuration, see attached screenshot. Each level cost some performance. It is limited to 10 because I think this is more than enough to view all required dependents without consuming a lot of resource and displaying you actually just Windows dlls depending on each other.

![image](https://github.com/user-attachments/assets/325fb5a8-442b-47d2-8607-bb63c9c6971d)

**Comment by mirh** [comment]
Duh, where did I have my head?
Sorry.

**Comment by mirh** [comment]
Ok so.. There's still something fishy going on.
Up to tree depth 9 of a dll, I have shell32.dll to load winmm.dll that loads winmmbase.dll, which then loads other stuff.
But if I set it to 10, winmmbase.dll doesn't show any children. I assume this is because the deeper analysis makes it resolve first inside of a previous chain (apparently `mfcore.dll < mftranscode.dll < windows.ui.immersive.dll < efsext.dll < efswrt.dll < kernelbase.dll < msvcrt.dll < advapi32.dll < comctl32.dll`), which in turn doesn't trigger nearly as much imports.
Surely this isn't by design? A lot of things are missed this way.

**Comment by hfiref0x** [comment]
I'll look more on this and probably additionally increase max level. Original Dependency Walker has depth 255 as limit and flags anything beyond that has circular dependency error.

**Comment by hfiref0x** [comment]
I'm not sure if there is a bug or not, it needs to be figured out. Or maybe entire handling of tree depth level need improvements. Thanks for letting me know, I'm adding this to the todo list.

**Comment by hfiref0x** [comment]
Dll depth has been increased. If you still experience problems with it - let me know in a new issue.

**Comment by i486** [comment]
@hfiref0x 

I was going to open a feature request titled "Module Tree Depth: 0", but this thread seems like a good place.

Right now, the minimum depth is 1, so it always scans/loads dependencies of the main file and their dependencies. I'd love an option for depth = 0, so it only show direct dependencies of the main file, without scanning for their child modules.

My primary reason is improved scan time, followed by a rare interest in second-level dependencies. 

Curious what you think!

**Comment by hfiref0x** [comment]
@i486 It is possible.

**Comment by hfiref0x** [comment]
@i486 
Please check the latest commit. Minimum depth is now 0.

**Comment by i486** [comment]
It's very fast now 👍. Thank you very much.
