### ISSUE TITLE
New feature: Identify unnamed exported functions by using PDBs.

### ISSUE THREAD

**Issue by MarekKnapek** [hfiref0x/WinDepends#2]
**Describe the bug**
Sometimes a module exports bunch of functions by ordinal but without any name. If you downloaded corresponding PDB, you could find the actual name of such functions.

**To Reproduce**
 - Open `WinDepends.exe`.
 - Analyze file, select `WinDepends.Core.x64.exe`.
 - Expand the tree on the left (should be already expanded by one level in my opinion).
 - Click on `CRYPT32.dll`.
 - See that bunch of functions are exported only by ordinal, but with no name.
 - If you downloaded corresponding PDB, you could find the actual name of such functions.
 - Maybe add new feature that such function names could be populated automagically. Maybe using different color or something so the user knows the names were in fact synthesized.
 - My tool does exactly this and I find it useful. Sadly I have no time to develop it further. https://github.com/MarekKnapek/DependencyViewer

**Expected behavior**
Download PDB, lookup the ordinal and display the function name.

**Screenshots**
![dwc](https://github.com/user-attachments/assets/3a8571d2-5857-4a9d-af77-50984c5e4c18)
![dwd](https://github.com/user-attachments/assets/c3b344b5-5a43-4ecc-8a9b-60a606c757fa)

**Desktop (please complete the following information):**
 - Windows Server 2022 x64 latest updates
 - Microsoft Windows [Version 10.0.20348.2849]

**Files**
no

**Additional context**
Feel free to borrow / steal source code and / or any ideas from my project.

**Comment by hfiref0x** [comment]
Added in https://github.com/hfiref0x/WinDepends/commit/34b2363579de28e4cd2bdee01f29440bb322a0a2

**Comment by hfiref0x** [comment]
Your dbghelp.dll is loaded from system32 folder.
