### ISSUE TITLE
Properties does not work sometimes.

### ISSUE THREAD

**Issue by MarekKnapek** [hfiref0x/WinDepends#3]
**Describe the bug**
Properties does not work sometimes.

**To Reproduce**
 - Have focus somewhere else than tree view on the left.
 - Such as on imported function or on exported function.
 - Press the Properties tool bar button or menu item.
 - Nothing happens.

**Expected behavior**
 - The commands (tool bar button and menu item) should do something.
 - Or they should be disabled.

**Screenshots**
no

**Desktop (please complete the following information):**
no

**Files**
no

**Additional context**
no

**Comment by hfiref0x** [comment]
Should be fixed in 3c56df7
