### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by hfiref0x** [hfiref0x/WinDepends#6]
Here are the list of features that are currently pending/considering implementation

+ #4 
+ #2 
+ #1 
+ #10
+ ~~User defined search path for user/kernel modules~~ https://github.com/hfiref0x/WinDepends/commit/96845260816b69103f8400a25fcba5b9362e81b4
+ ~~Kernel modules search order as separate tab~~ https://github.com/hfiref0x/WinDepends/commit/96845260816b69103f8400a25fcba5b9362e81b4
+ ~~Server configuration tab with server status and reconnect functionality~~ https://github.com/hfiref0x/WinDepends/commit/96845260816b69103f8400a25fcba5b9362e81b4
+ Complete help file as PDF and markdown, with a link to it from WinDepends help menu/project readme
+ ~~Make server dbgstats command configurable from WinDepends configuration and disable it by default~~~~Rework it completely~~https://github.com/hfiref0x/WinDepends/commit/b9a3e7167453b8ca04071f079cd03a6f56cffabf
+ ~~Add an analysis setting dialog with default values taken from WinDepends configuration~~https://github.com/hfiref0x/WinDepends/commit/ebb1312a59360b46d0075d524a1af76da4ed89f5
+ ~~Support legacy apisets V/2V4 (requested)~~ https://github.com/hfiref0x/WinDepends/commit/a680cf0038120c1606312633f610f64244c8083a

**Comment by i486** [comment]
Not creating a new thread for this, but it would be helpful to have WinDepends.Core.x64.exe automatically terminate (or an option to do so) when the main WinDepends.exe process is closed. Currently, the core process continues running even after closing the main application.

**Comment by hfiref0x** [comment]
> Not creating a new thread for this, but it would be helpful to have WinDepends.Core.x64.exe automatically terminate (or an option to do so) when the main WinDepends.exe process is closed. Currently, the core process continues running even after closing the main application.

If there is no clients (WinDepends.exe) attached it will self-terminate in 30 seconds.

**Comment by sergeevabc** [comment]
Guys, what is the purpose of `WinDepends.Core.x64.exe`?
I launch it and see no windows, no console output.
