### ISSUE TITLE
An archive with the binaries is detected as malicious by Defender

### ISSUE THREAD

**Issue by aibaranov** [hfiref0x/WinDepends#8]
Hello

Thank you for another useful project, just wanted to inform that the archive with the binaries from the Releases section is detected as malicious by Defender and can't be downloaded.

![Screenshot 2024-12-04 205852](https://github.com/user-attachments/assets/e0bdc218-8d76-44fb-b843-9f56ca269f8e)

**Comment by hfiref0x** [comment]
You can always build from source.

I can't do anything with Microsoft schizophrenic next-gen AV and there are no "scripts" included in this zip.
